### ISSUE TITLE
Annotation Backend

### ISSUE THREAD

**Issue by sirexeclp** [team-folivora/annoto#5]
As data provider i want to be able to provide images so that they can be shown to medical experts to be annotated.

### Acceptance  Critera
- [x]  input and output in directory on filesystem #11 
- [x] annotation can be saved #13
- [x] annotation is linked to the input data
- [x] annotation can be retrieved via the API #43
