### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by sirexeclp** [team-folivora/annoto#8]
As a data provider i want the annotations to contain the necessary metadata to be compliant with regulations regarding labeling of training data.

### Acceptance Criteria

- [x]  metadata is saved with the annotations
    - [x] user-id #16 
    - [x] proof of competency #17 
    - [x] proof of training #18 
    - [x] proof of attentiveness #19
